[book]
authors = ["Daniel Fox"]
language = "en"
multilingual = false
src = "src"
title = "Iterative Methods Blog"

[output.html]
mathjax-support = true
default-theme = "coal"
preferred-dark-theme = "navy"

